discipula_informe_estudiantes_red:
    pattern: /informe_estudiantes_red
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_estudiantes_red}
    requirements:
        _method: POST
        
discipula_informe_docentes:
    pattern: /informe_docentes_all
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_docentes_all}
    requirements:
        _method: POST
        
discipula_informe_aula:
    pattern: /informe_aula_all
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_aula_all}
    requirements:
        _method: POST
        
discipula_informe_asignacion_detalle:
    pattern: /informe_asignacion_detalle
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_asignacion_detalle}
    requirements:
        _method: POST
        
disciplina_informe_semanal_indeli_view:
    pattern: /informe_semanal_indeli_view
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_semanal_indeli_view}
    requirements:
        _method: GET
        
disciplina_informe_semanal_indeli_service:
    pattern: /informe_semanal_indeli_service
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_semanal_indeli_service}
    requirements:
        _method: POST
        
disciplina_informe_alumnos_indeli_view:
    pattern: /informe_alumnos_indeli_view
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_alumnos_indeli_view}
    requirements:
        _method: GET
        
disciplina_informe_alumnos_indeli_service:
    pattern: /informe_alumnos_indeli_service
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_semanal_alumnos_service}
    requirements:
        _method: POST