discipula_informe_estudiantes_red:
    pattern: /informe_estudiantes_red
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_estudiantes_red}
    requirements:
        _method: POST
        
discipula_informe_docentes:
    pattern: /informe_docentes_all
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_docentes_all}
    requirements:
        _method: POST
        
discipula_informe_aula:
    pattern: /informe_aula_all
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_aula_all}
    requirements:
        _method: POST
        
discipula_informe_asignacion_detalle:
    pattern: /informe_asignacion_detalle
    defaults: {_controller: AEDiscipulaBundle:Informe:informe_asignacion_detalle}
    requirements:
        _method: POST