matricula_view:
    pattern:  /matricula_view
    defaults: { _controller: AEDiscipulaBundle:Matricula:view }
    requirements:
        _method: GET
        
matricula_save:
    pattern:  /matricula_save
    defaults: { _controller: AEDiscipulaBundle:Matricula:save }
    requirements:
        _method: POST

matricula_edit:
    pattern:  /matricula_edit
    defaults: { _controller: AEDiscipulaBundle:Matricula:edit }
    requirements:
        _method: POST
        
        
matricula_asistencia:
    pattern:  /matricula_asistencia
    defaults: { _controller: AEDiscipulaBundle:Matricula:asistencia }
    requirements:
        _method: POST
        
matricula_terminar:
    pattern:  /matricula_terminar
    defaults: { _controller: AEDiscipulaBundle:Matricula:terminar }
    requirements:
        _method: POST