ae_discipula_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AEDiscipulaBundle:Default:index }

curso_discipula_routing:
    resource: "@AEDiscipulaBundle/Resources/config/curso_routing.yml"
    
docente_discipula_routing:
    resource: "@AEDiscipulaBundle/Resources/config/docente_routing.yml"
    
estudiante_discipula_routing:
    resource: "@AEDiscipulaBundle/Resources/config/estudiante_routing.yml"
    
aula_discipula_routing:
    resource: "@AEDiscipulaBundle/Resources/config/aula_routing.yml"
    
asistencia_discipula_routing:
    resource: "@AEDiscipulaBundle/Resources/config/asistencia_routing.yml"
    
matricula_discipula_routing:
    resource: "@AEDiscipulaBundle/Resources/config/matricula_routing.yml"
    
asignacion_discipula_routing:
    resource: "@AEDiscipulaBundle/Resources/config/asignacion_routing.yml"