parameters:
#    ae_discipula.example.class: AE\DiscipulaBundle\Example

services:
#    ae_discipula.example:
#        class: %ae_discipula.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
