asignarconsolidador_view:
    pattern:  /asignarconsolidador_view
    defaults: { _controller: AEConsolidaBundle:AsignarConsolidador:view }
    requirements:
        _method: GET
        
asignarconsolidador_save:
    pattern:  /asignarconsolidador_save
    defaults: { _controller: AEConsolidaBundle:AsignarConsolidador:save }
    requirements:
        _method: POST

consolidado_off:
    pattern:  /consolidado_off
    defaults: { _controller: AEConsolidaBundle:AsignarConsolidador:off }
    requirements:
        _method: POST