informe_resumido_view:
    pattern:  /informe_resumido_view
    defaults: { _controller: AEConsolidaBundle:Informe:resumido_view }
    requirements:
        _method: GET
        
informe_resumido_service:
    pattern:  /informe_resumido_service
    defaults: { _controller: AEConsolidaBundle:Informe:resumido_service }
    requirements:
        _method: POST

informe_detallado_view:
    pattern:  /informe_detallado_view
    defaults: { _controller: AEConsolidaBundle:Informe:detallado_view }
    requirements:
        _method: GET
        
informe_detallado_service:
    pattern:  /informe_detallado_service
    defaults: { _controller: AEConsolidaBundle:Informe:detallado_service }
    requirements:
        _method: POST
        
informe_anual_tri_view:
    pattern:  /informe_anual_tri_view
    defaults: { _controller: AEConsolidaBundle:Informe:anual_tri_view }
    requirements:
        _method: GET
        
informe_anual_tri_service:
    pattern:  /informe_anual_tri_service
    defaults: { _controller: AEConsolidaBundle:Informe:anual_tri_service }
    requirements:
        _method: POST