ae_consolida_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AEConsolidaBundle:Default:index }
    
leche_consolida_routing:
    resource: "@AEConsolidaBundle/Resources/config/leche_routing.yml"

consolidador_consolida_routing:
    resource: "@AEConsolidaBundle/Resources/config/consolidador_routing.yml"
    
asignarconsolidador_consolida_routing:
    resource: "@AEConsolidaBundle/Resources/config/asignarconsolidador_routing.yml"
