parameters:
#    ae_consolida.example.class: AE\ConsolidaBundle\Example

services:
#    ae_consolida.example:
#        class: %ae_consolida.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
