servicio_bautizos_all:
  pattern: /bautizos_all
  defaults: {_controller: AEServiciosBundle:SecretariaServicio:bautizo_all}
  requirements:
    _method: GET

servicio_encuentros_all:
  pattern: /encuentros_all
  defaults: {_controller: AEServiciosBundle:SecretariaServicio:encuentros_all}
  requirements:
    _method: GET