admincelula_view:
    pattern:  /admincelula_view
    defaults: { _controller: AEEnviaBundle:AdminCelula:view }
    requirements:
        _method: GET
        
admincelula_enrolar:
    pattern:  /admincelula_enrolar
    defaults: { _controller: AEEnviaBundle:AdminCelula:enrolar }
    requirements:
        _method: POST
        
        
admincelula_desactivar:
    pattern:  /admincelula_desactivar
    defaults: { _controller: AEEnviaBundle:AdminCelula:desactivar }
    requirements:
        _method: POST