informe_semanal_view:
    pattern:  /informe_semanal_view
    defaults: { _controller: AEEnviaBundle:Informe:informe_semanal_view }
    requirements:
        _method: GET
        
informe_semanal_service:
    pattern:  /informe_semanal_service
    defaults: { _controller: AEEnviaBundle:Informe:informe_semanal_service }
    requirements:
        _method: POST
        
informe_celulograma_view:
    pattern:  /informe_celulograma_view
    defaults: { _controller: AEEnviaBundle:Informe:informe_celulograma_view }
    requirements:
        _method: GET
        
        
informe_celulograma_service:
    pattern:  /informe_celulograma_service
    defaults: { _controller: AEEnviaBundle:Informe:informe_celulograma_service }
    requirements:
        _method: POST
        
        
informe_lideres_celula_view:
    pattern:  /informe_lideres_celula_view
    defaults: { _controller: AEEnviaBundle:Informe:informe_lideres_celula_view }
    requirements:
        _method: GET
        
informe_lideres_celula_service:
    pattern:  /informe_lideres_celula_service
    defaults: { _controller: AEEnviaBundle:Informe:informe_lideres_celula_service }
    requirements:
        _method: POST