liderazgo_envia_view:
    pattern:  /liderazgo_view
    defaults: { _controller: AEEnviaBundle:Liderazgo:view }
    requirements:
        _method: GET
        
agregar_lider_save:
    pattern:  /agregar_lider_save
    defaults: { _controller: AEEnviaBundle:Liderazgo:agregar_lider_save }
    requirements:
        _method: POST
        
eliminar_lider_save:
    pattern:  /eliminar_lider_save
    defaults: { _controller: AEEnviaBundle:Liderazgo:eliminar_lider_save }
    requirements:
        _method: POST
        