ae_configurar:
    resource: "@AEConfigurarBundle/Resources/config/routing.yml"
    prefix:   /

ae_data:
    resource: "@AEDataBundle/Resources/config/routing.yml"
    prefix:   /
    
_user_bundle:
  resource: "@UserBundle/Resources/config/routing.yml"
  prefix: /

