ae_secretaria:
    resource: "@AESecretariaBundle/Resources/config/routing.yml"
    prefix:   /secretaria/

ae_discipula:
    resource: "@AEDiscipulaBundle/Resources/config/routing.yml"
    prefix:   /discipula/

ae_consolida:
    resource: "@AEConsolidaBundle/Resources/config/routing.yml"
    prefix:   /consolida/

ae_envia:
    resource: "@AEEnviaBundle/Resources/config/routing.yml"
    prefix:   /envia/

ae_tool:
    resource: "@AEToolBundle/Resources/config/routing.yml"
    prefix:   /tool/

ae_contabilidad:
    resource: "@AEContabilidadBundle/Resources/config/routing.yml"
    prefix:   /contabilidad/


ae_gana:
    resource: "@AEGanaBundle/Resources/config/routing.yml"
    prefix:   /gana/

ae_services:
    resource: "@AEServicesBundle/Resources/config/routing.yml"
    prefix:   /services/

ae_configurar:
    resource: "@AEConfigurarBundle/Resources/config/routing.yml"
    prefix:   /

ae_data:
    resource: "@AEDataBundle/Resources/config/routing.yml"
    prefix:   /
    
_user_bundle:
  resource: "@UserBundle/Resources/config/routing.yml"
  prefix: /
  
ae_ganar:
    resource: "@AEGanarBundle/Resources/config/routing.yml"
    prefix:   /ganar/

ae_servicios:
    resource: "@AEServiciosBundle/Resources/config/routing.yml"
    prefix:   /