security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        #main:
            #pattern:  ^/
            #security: false

        #login:
        secured_area:
            #pattern:  ^/demo/secured/login$      
            form_login:
                check_path: /login_check #_security_check
                login_path: /login #_demo_login
                provider: fos_userbundle
                
            logout:
                path:   /logout #_demo_logout
                target: / #_demo
               
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
