security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        #ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_PASTOR_EJECUTIVO: [ROLE_PASTOR_ASOCIADO]
        ROLE_PASTOR_ASOCIADO: [ROLE_GANAR, ROLE_CONSOLIDAR, ROLE_DISCIPULAR,ROLE_ENVIAR]
        ROLE_ENVIAR: [ROLE_MISIONERO]
        ROLE_MISIONERO: [ROLE_USER]
        ROLE_GANAR: [ROLE_USER,ROLE_LIDER_RED]
        ROLE_CONSOLIDAR: [ROLE_LIDER_RED]
        ROLE_LIDER_RED: [ROLE_LIDER,ROLE_CONSOLIDADOR]
        ROLE_CONSOLIDADOR: [ROLE_USER]
        ROLE_LIDER: [ROLE_LIDER12]
        ROLE_LIDER12:  [ROLE_LIDER144]
        ROLE_LIDER144: [ROLE_LIDER1728]
        ROLE_LIDER1728: [ROLE_LIDERSIN]
        ROLE_LIDERSIN: [ROLE_USER]
        ROLE_DISCIPULAR: [ROLE_PROFESOR]
        ROLE_PROFESOR: [ROLE_ESTUDIANTE]
        ROLE_ESTUDIANTE: [ROLE_USER]
        ROLE_SECRE: [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_PASTOR_EJECUTIVO,ROLE_SECRE]

    providers:
       fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        #main:
            #pattern:  ^/
            #security: false

        #login:
        main:
            #pattern:  ^/demo/secured/login$      
            #pattern: /.*
            form_login:
                check_path: /login_check #_security_check
                login_path: /login #_demo_login
                provider: fos_userbundle
#                target: /gana/nuevo
                
            logout:
                path:   /logout #_demo_logout
                target: /login
               
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: /main , roles: ROLE_ADMIN}
        #- { path: /gana/* , roles: ROLE_ADMIN}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
