parameters:
#    ae_contabilidad.example.class: AE\ContabilidadBundle\Example

services:
#    ae_contabilidad.example:
#        class: %ae_contabilidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
