parameters:
#    ae_secretaria.example.class: AE\SecretariaBundle\Example

services:
#    ae_secretaria.example:
#        class: %ae_secretaria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
