main:
    pattern:  /main
    defaults: { _controller: AEConfigurarBundle:Default:index }
    
inicio:
    pattern: /
    defaults: { _controller: AEConfigurarBundle:Default:inicio}
    
permisos_configurar_routing:
    resource: "@AEConfigurarBundle/Resources/config/permisos_routing.yml"