parameters:
#    ae_configurar.example.class: AE\ConfigurarBundle\Example

services:
#    ae_configurar.example:
#        class: %ae_configurar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
