ae_gana_informe_semanal:
    pattern: /informe_semanal
    defaults: {_controller: AEGanaBundle:Informe:semanal}
    
ae_gana_informe_detallado_view:
    pattern: /informe_detallado_view
    defaults: {_controller: AEGanaBundle:Informe:detallado_view}
    requirements:
        _method: GET
        
ae_gana_informe_detallado_service:
    pattern: /informe_detallado_service
    defaults: {_controller: AEGanaBundle:Informe:detallado_service}
    requirements:
        _method: POST
        
ae_gana_informe_semanal_view:
    pattern: /informe_semanal_view
    defaults: {_controller: AEGanaBundle:Informe:semanal_view}
    requirements:
        _method: GET
        
ae_gana_informe_semanal_service:
    pattern: /informe_semanal_view
    defaults: {_controller: AEGanaBundle:Informe:semanal_service}
    requirements:
        _method: POST

ae_gana_informe_tri_anual_view:
    pattern: /informe_tri_anual_view
    defaults: {_controller: AEGanaBundle:Informe:informe_tri_anual_view}
    requirements:
        _method: GET
        
ae_gana_informe_tri_anual_service:
    pattern: /informe_tri_anual_service
    defaults: {_controller: AEGanaBundle:Informe:informe_tri_anual_service}
    requirements:
        _method: POST  
        
        