
ae_gana_persona:
    pattern: /nueva_persona
    defaults: { _controller: AEGanaBundle:Registrar:registrar_persona}
    requirements:
        _method: POST


        
ae_gana_view:
    pattern: /nuevo
    defaults: {_controller: AEGanaBundle:Registrar:nuevo}