
ae_gana_persona:
    pattern: /nueva_persona
    defaults: { _controller: AEGanaBundle:Registrar:registrar_persona}
    requirements:
        _method: POST

ae_gana_test:
    pattern: /registrar_test
    defaults: { _controller: AEGanaBundle:Registrar:test}
    requirements:
        _method: GET
        
ae_gana_view:
    pattern: /nuevo
    defaults: {_controller: AEGanaBundle:Registrar:nuevo}