ae_gana_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AEGanaBundle:Default:index }
    
gana_registrar_routing:    
    resource: "@AEGanaBundle/Resources/config/registrar_routing.yml"
    
gana_editar_routing:    
    resource: "@AEGanaBundle/Resources/config/editar_routing.yml"
  
gana_eliminar_routing:    
    resource: "@AEGanaBundle/Resources/config/eliminar_routing.yml"
    
gana_informes_routing:    
    resource: "@AEGanaBundle/Resources/config/informes_routing.yml"
    
ae_gana_busqueda:
    pattern: /busqueda
    defaults: { _controller: AEGanaBundle:Default:busqueda}
    
ae_gana_persona_vista:
    pattern: /vista_persona/{id}
    defaults: {_controller: AEGanaBundle:Default:view}
    
gana_dashboard_routing:
    resource: "@AEGanaBundle/Resources/config/dashboard_routing.yml"