ae_gana_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AEGanaBundle:Default:index }
    
gana_registrar_routing:    
    resource: "@AEGanaBundle/Resources/config/registrar_routing.yml"
    
    
ae_gana_busqueda:
    pattern: /busqueda
    defaults: { _controller: AEGanaBundle:Default:busqueda}
