services_lider_red:
  pattern: /lista_lider_red
  defaults: {_controller: AEServicesBundle:ConfigurarServices:lista_lider_red}
  requirements:
    _method: GET
    
services_pastor:
  pattern: /lista_pastor
  defaults: {_controller: AEServicesBundle:ConfigurarServices:lista_pastor}
  requirements:
    _method: GET
    
service_lider_celula_all:
    pattern: /lider_celula_all/{red}
    defaults: { _controller: AEServicesBundle:ConfigurarServices:lider_celula_all}
    requirements:
        _method: GET
    
service_lider_red_by_red:
    pattern: /lider_red/{red}
    defaults: {_controller: AEServicesBundle:ConfigurarServices:lider_red}