services_consolidador_init:
  pattern: /lista_consolidador_init
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidador_init}
  requirements:
    _method: GET
    
services_consolidador_all:
  pattern: /lista_consolidador_all
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidador_all}
  requirements:
    _method: GET
    
services_consolidador_red:
  pattern: /lista_consolidador_red/{red}
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidador_red}
  requirements:
    _method: GET

services_miembro_init_no_consolidador:
  pattern: /lista_miembro_init_no_consolidador
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_miembro_init_no_consolidador}
  requirements:
    _method: GET
    
services_miembro_all_no_consolidador:
  pattern: /lista_miembro_all_no_consolidador
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_miembro_all_no_consolidador}
  requirements:
    _method: GET
    
services_miembro_red_no_consolidador:
  pattern: /lista_miembro_red_no_consolidador/{red}
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_miembro_red_no_consolidador}
  requirements:
    _method: GET
    
    
services_sin_consolidar_red:
  pattern: /lista_sin_consolidar_red/{red}
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_sin_consolidar_red}
  requirements:
    _method: GET
    
services_consolidando_red:
  pattern: /lista_consolidando_red/{red}
  defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidando_red}
  requirements:
    _method: GET
    
services_leche_espiritual:
    pattern: /lista_leche
    defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_leche}
    requirements:
        _method: GET
        
        
services_consolidando_red_consolidador:
    pattern: /lista_consolidando_red_consolidador/{red}/{consolidador}
    defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidando_red_consolidador}
    requirements:
        _method: GET
        
services_consolidando_red_consolidador_fecha:
    pattern: /lista_consolidando_red_consolidador/{red}/{consolidador}/{inicio}/{fin}
    defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidando_red_consolidador_fecha}
    requirements:
        _method: GET
        
services_consolidado_red_consolidador:
    pattern: /lista_consolidado_red_consolidador/{red}/{consolidador}
    defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidado_red_consolidador}
    requirements:
        _method: GET
        
services_consolidado_red_consolidador_fecha:
    pattern: /lista_consolidado_red_consolidador/{red}/{consolidador}/{inicio}/{fin}
    defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_consolidado_red_consolidador_fecha}
    requirements:
        _method: GET
        
services_descartar_red_consolidador:
    pattern: /lista_descartar_red_consolidador/{red}/{consolidador}
    defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_descartar_red_consolidador}
    requirements:
        _method: GET
        
services_descartar_red_consolidador_fecha:
    pattern: /lista_descartar_red_consolidador/{red}/{consolidador}/{inicio}/{fin}
    defaults: {_controller: AEServicesBundle:ConsolidarServices:lista_descartar_red_consolidador_fecha}
    requirements:
        _method: GET       

services_temas_leche_consolidado:
    pattern: /temas_leche_consolidado/{consolidado}
    defaults: {_controller: AEServicesBundle:ConsolidarServices:temas_leche_consolidado}
    requirements:
        _method: GET