services_miembros_nodocente_autocomplete_red:
    pattern: /miembros_nodocente_autocomplete_red/{red}
    defaults: {_controller: AEServicesBundle:DiscipularServices:miembros_nodocente_autocomplete_red}
    requirements:
        _method: GET
        
services_persona_noestudiante_autocomplete_red:
    pattern: /persona_noestudiante_autocomplete_red/{red}
    defaults: {_controller: AEServicesBundle:DiscipularServices:persona_noestudiante_autocomplete_red}
    requirements:
        _method: GET

services_cursos_option_all:
    pattern: /cursos_option_all
    defaults: {_controller: AEServicesBundle:DiscipularServices:cursos_option_all}
    requirements:
        _method: GET
        
services_cursos_all_table:
    pattern: /cursos_all_table
    defaults: {_controller: AEServicesBundle:DiscipularServices:cursos_all_table}
    requirements:
        _method: GET
        
services_profesor_all_table:
    pattern: /profesor_all_table
    defaults: {_controller: AEServicesBundle:DiscipularServices:profesor_all_table}
    requirements:
        _method: GET
        
services_estudiante_red_table:
    pattern: /estudiante_red/{red}
    defaults: {_controller: AEServicesBundle:DiscipularServices:estudiante_red_table}
    requirements:
        _method: GET
        
services_estudiante_activo_red_table:
    pattern: /estudiante_activo_red/{red}
    defaults: {_controller: AEServicesBundle:DiscipularServices:estudiante_activo_red_table}
    requirements:
        _method: GET
        
services_aula_all_table:
    pattern: /aula_all_table
    defaults: {_controller: AEServicesBundle:DiscipularServices:aula_all_table}
    requirements:
        _method: GET
        
#profesores activos
services_profesor_option:
    pattern: /profesor_option
    defaults: {_controller: AEServicesBundle:DiscipularServices:profesor_option}
    requirements:
        _method: GET
#curso activo        
services_curso_option:
    pattern: /curso_option
    defaults: {_controller: AEServicesBundle:DiscipularServices:curso_option}
    requirements:
        _method: GET        
#aula activa

services_aula_option:
    pattern: /aula_option
    defaults: {_controller: AEServicesBundle:DiscipularServices:aula_option}
    requirements:
        _method: GET
        
services_curso_profesor_tabla:
    pattern: /curso_profesor_tabla/{profesor}/{curso}
    defaults: {_controller: AEServicesBundle:DiscipularServices:curso_profesor_tabla}
    requirements:
        _method: GET
        
services_detalle_pca_all_tabla:
    pattern: /detalle_pca_all_tabla
    defaults: {_controller: AEServicesBundle:DiscipularServices:detalle_pca_all_tabla}
    requirements:
        _method: GET
        
services_matriculados_detalle:
    pattern: /matriculados_detalle/{detalle}
    defaults: {_controller: AEServicesBundle:DiscipularServices:matriculados_detalle}
  
services_table_matriculados_detalle:
    pattern: /table_matriculados_detalle/{detalle}/{num_lecciones}
    defaults: {_controller: AEServicesBundle:DiscipularServices:table_matriculados_detalle}
    requirements:
        _method: GET
    
services_option_sin_aplicar_detalle_pca:
    pattern: /option_sin_aplicar_detalle_pca/{detalle}
    defaults: {_controller: AEServicesBundle:DiscipularServices:option_sin_aplicar_detalle_pca}
    requirements:
        _method: GET
        
services_table_matriculados_detalle_pca:
    pattern: /table_matriculados_detalle_pca/{detalle}
    defaults: {_controller: AEServicesBundle:DiscipularServices:table_matriculados_detalle_pca}
    requirements:
        _method: GET