services_ultimas_celula_table:
  pattern: /ultimas_celula_table
  defaults: {_controller: AEServicesBundle:EnviarServices:ultimas_celula_table}
  requirements:
    _method: GET
    
services_check_lider_red:
    pattern: /check_lider_red/{red}
    defaults: {_controller: AEServicesBundle:EnviarServices:check_lider_red}
    requirements:
        _method: GET
        
services_hijos_de_lider_option:
    pattern: /hijos_de_lider_option/{lider}/{tipo}
    defaults: {_controller: AEServicesBundle:EnviarServices:hijos_de_lider_option}
    requirements:
        _method: GET
        
services_all_celulas_red_tabla:
    pattern: /all_celulas_red_tabla/{red}
    defaults: {_controller: AEServicesBundle:EnviarServices:all_celulas_red_tabla}
    requirements:
        _method: GET
        
services_sin_celula_red:
    pattern: /sin_celula_red/{red}
    defaults: {_controller: AEServicesBundle:EnviarServices:sin_celula_red}
    requirements:
        _method: GET
        
services_con_celula_red:
    pattern: /con_celula_red/{red}/{celula}
    defaults: {_controller: AEServicesBundle:EnviarServices:con_celula_red}
    requirements:
        _method: GET
        
services_celulas_menos_red:
    pattern: /celulas_menos/{red}/{celula}/{tipo}
    defaults: {_controller: AEServicesBundle:EnviarServices:celulas_menos}
    requirements:
        _method: GET
        
services_tema_celulas_tabla:
    pattern: /tema_celulas_tabla
    defaults: {_controller: AEServicesBundle:EnviarServices:tema_celulas_tabla}
    requirements:
        _method: GET
        
services_aplicacion_inbox_tema_red:
    pattern: /aplicacion_inbox_tema_red/{red}
    defaults: {_controller: AEServicesBundle:EnviarServices:aplicacion_inbox_tema_red}
    requirements:
        _method: GET
        
services_aplicacion_sent_tema_red:
    pattern: /aplicacion_sent_tema_red/{red}
    defaults: {_controller: AEServicesBundle:EnviarServices:aplicacion_sent_tema_red}
    requirements:
        _method: GET
        
        
services_aplicacion_asistencia:
    pattern: /aplicacion_asistencia/{app}
    defaults: {_controller: AEServicesBundle:EnviarServices:aplicacion_asistencia}
    requirements:
        _method: GET