## YAML Template.
---
services_red:
  pattern: /lista_red
  defaults: {_controller: AEServicesBundle:GanarServices:lista_red}
  requirements:
    _method: GET
    
services_lugar:
    pattern: /lista_lugar
    defaults: {_controller: AEServicesBundle:GanarServices:lista_lugar}
    requirements:
        _method: GET