services_red:
  pattern: /lista_red
  defaults: {_controller: AEServicesBundle:GanarServices:lista_red}
  requirements:
    _method: GET
    
services_lugar:
    pattern: /lista_lugar
    defaults: {_controller: AEServicesBundle:GanarServices:lista_lugar}
    requirements:
        _method: GET
        
services_celula:
    pattern: /lista_celula/{red}
    defaults: {_controller: AEServicesBundle:GanarServices:lista_celula}
    
services_personas_init:
    pattern: /personas_init
    defaults: {_controller: AEServicesBundle:GanarServices:personas_init}
    requirements:
        _method: GET
        
        
services_personas_all:
    pattern: /personas_all
    defaults: {_controller: AEServicesBundle:GanarServices:personas_all}
    
services_personas_filtro_fechas:
    pattern: /personas_filtro/{red}/{ini}/{fin}
    defaults: {_controller: AEServicesBundle:GanarServices:personas_filtro_fecha_red}
    
services_personas_filtro_red:
    pattern: /personas_filtro_red/{red}
    defaults: {_controller: AEServicesBundle:GanarServices:personas_filtro_red}
        
        
services_ganadores_autocomplete_all:
    pattern: /ganador_autocomplete_all
    defaults: { _controller: AEServicesBundle:GanarServices:ganador_autocomplete_all}
    requirements:
        _method: GET
        
services_ganadores_autocomplete_red:
    pattern: /ganador_autocomplete_red/{red}
    defaults: {_controller: AEServicesBundle:GanarServices:ganador_autocomplete_red}
    requirements:
        _method: GET