ae_services_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AEServicesBundle:Default:index }
    
ganar_services_routing:
    resource: "@AEServicesBundle/Resources/config/ganar_services_routing.yml"

   
configurar_services_routing:
    resource: "@AEServicesBundle/Resources/config/configurar_services_routing.yml"
    
secretaria_services_routing:
    resource: "@AEServicesBundle/Resources/config/secretaria_services_routing.yml"

discipular_services_routing:
    resource: "@AEServicesBundle/Resources/config/discipular_services_routing.yml"
