services_sinbautizo_autocomplete_red:
    pattern: /sinbautizo_autocomplete_red/{red}
    defaults: {_controller: AEServicesBundle:Secretaria:sinbautizo_autocomplete_red}
    requirements:
        _method: GET
        
        
services_personas_autocomplete_red:
    pattern: /personas_autocomplete_red/{red}
    defaults: {_controller: AEServicesBundle:Secretaria:personas_autocomplete_red}
    requirements:
        _method: GET
        
servicio_bautizos_all:
  pattern: /bautizos_all
  defaults: {_controller: AEServicesBundle:Secretaria:bautizo_all}
  requirements:
    _method: GET
    
servicio_encuentro_all:
  pattern: /encuentro_all
  defaults: {_controller: AEServicesBundle:Secretaria:encuentro_all}
  requirements:
    _method: GET