services_sinbautizo_autocomplete_red:
    pattern: /sinbautizo_autocomplete_red/{red}
    defaults: {_controller: AEServicesBundle:Secretaria:sinbautizo_autocomplete_red}
    requirements:
        _method: GET