parameters:
#    ae_services.example.class: AE\ServicesBundle\Example

services:
#    ae_services.example:
#        class: %ae_services.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
